-- ═════════════════════════════════════════════════════════════════════════════
-- Solicitudes de edicion: foto de los valores al momento de pedir (2026-09-15)
--
-- El administrador veia QUE campos le pedian editar, pero no CUANTO valen hoy.
-- Aprobaba a ciegas: "quiere cambiar la hora de salida" no dice si la hora
-- actual es un error evidente o un dato correcto.
--
-- Esta columna guarda el valor que tenia cada campo pedido EN EL MOMENTO de la
-- solicitud. Dos motivos para congelarlo aqui y no leerlo en vivo al abrir la
-- bandeja:
--
--   1. El historial. Si se leyera en vivo, despues de la correccion el
--      administrador veria el valor NUEVO y no habria forma de saber que se
--      cambio. La foto es la unica prueba de como estaba antes.
--   2. La respuesta puede cambiar entre que se pide y se atiende.
--
-- Forma del JSON (contempla repetidores: un campo tiene un valor POR FILA):
--   [
--     {
--       "element_id": "...",
--       "label": "465_HORA SALIDA",
--       "repeater_id": "rep",          -- null si es un campo suelto
--       "valores": [
--         {"fila": 0, "valor": "10:22"},
--         {"fila": 1, "valor": "16:00"}
--       ]
--     }
--   ]
--
-- Aditiva y opcional: las solicitudes anteriores quedan con NULL y la bandeja
-- simplemente no les muestra la foto.
--
-- APLICADO EN: forms_sfisas @ localhost
-- PENDIENTE EN: prod (forms_sfisas_dev @ 207.246.75.205)
-- ═════════════════════════════════════════════════════════════════════════════

ALTER TABLE response_edit_requests
    ADD COLUMN IF NOT EXISTS snapshot TEXT NULL;
